---
- name: pre auth
  hosts: all
  connection: local
  vars_files:
    - "group_vars/{{ group_names[0] }}_ssl.yml"
  roles:
    - role: preauth


- name: mongo backup
  hosts: all
  remote_user: root
  gather_facts: no
  roles:
    - role: mongo
