

- name: preinstall tasks
  hosts: all
  connection: local
  roles:
    - preinstall

# - name: initial docker configuration
#   hosts: all
#   remote_user: '{{ setup_common_deploy_user_name }}'
#   gather_facts: no
#   # strategy: debug
#   vars:
#     docker_init: true
#   roles:
#     # - role: configs
#     - role: mongo
